apps/modelos/urls.py
from django.urls import path

from apps.modelos.views.paciente.views import (
   PacienteListView, PacienteCreateView,
   PacienteUpdateView,
)

from apps.modelos.views.mamografia.views import (
   MamografiaUploadView, MamografiaListView,
   MamografiaCreate, MamografiaUpdateView
)

app_name = "core"

urlpatterns = [
   # path('modelo/', home, name='home'),
   # Pacientes
   path("pacientes/", PacienteListView.as_view(), name="pacientes_list"),
   path("paciente/", PacienteCreateView.as_view(), name="pacientes_create"),
   path("paciente/<int:pk>/", PacienteUpdateView.as_view(), name="pacientes_create"),

   # Mamografia
   path('mamografia/<str:external>/', MamografiaListView.as_view(), name='mamografia_list'),
   path('mamografia/predict/<str:external>/', MamografiaUploadView.as_view(), name='mamografia_predict'),
   path('mamografia/create/<int:result>/<int:mamografia>/', MamografiaCreate.as_view(), name='mamografia_create'),
   path('mamografia/edit/<int:pk>/', MamografiaUpdateView.as_view(), name='mamografia_create'),
   
   
   
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.modelos.views.login.views import LoginView
from apps.modelos.views.signin.views import SignUpView
from django.contrib.auth.views import LogoutView

from apps.home.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='index'),
    path('core/', include('apps.modelos.urls')),
    # LISTAR MAMOGRAFIA
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/body.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        {% include 'partials/navbar.html' %}
        {% include 'partials/sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>{{ title }}</h1>
                        </div>
                        <div class="col-sm-6">
                            {% block body_url %}
                                <ol class="breadcrumb float-sm-right">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item"><a href="#">Layout</a></li>
                                    <li class="breadcrumb-item active">Fixed Layout</li>
                                </ol>
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </section>
            <!-- Main content -->
            <section class="content">
                {% block content %}
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                <!-- Default box -->
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title">Title</h3>
                                        <div class="card-tools">
                                            <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                                    title="Collapse">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                            <button type="button" class="btn btn-tool" data-card-widget="remove"
                                                    title="Remove">
                                                <i class="fas fa-times"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        Start creating your amazing application!
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        Footer
                                    </div>
                                    <!-- /.card-footer-->
                                </div>
                                <!-- /.card -->
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        {% include 'partials/footer.html' %}

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- DataTables  & Plugins -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.2.0/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
     {% block javascript %}
 
     {% endblock %}
    </body>
{% endblock %}

templates/partials/footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.2.0
    </div>
    <strong>Copyright &copy; 2023 Ramoncito.</strong> All rights reserved.
</footer>

templates/partials/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
               
            </div>
        </li>

       
    </ul>
</nav>
<!-- /.navbar -->

templates/partials/sidebar.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar main-sidebar-custom sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'core:pacientes_list' %}" class="brand-link">
        <img src="{% static 'lib/adminlte-3.2.0/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Sistema Medico</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false"> 
                <li class="nav-item">
                    <a href="{% url 'core:pacientes_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Pacientes
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->

    <div class="sidebar-custom">
        <a href="{% url 'logout' %}" class="btn btn-link">Cerrar Sesión <i class="fas fa-times"></i></a>
    </div>
    <!-- /.sidebar-custom -->
</aside>