apps/modelos/urls.py
from django.urls import path

from apps.modelos.views.paciente.views import (
   PacienteListView, PacienteCreateView,
   PacienteUpdateView,
)

from apps.modelos.views.mamografia.views import (
   MamografiaUploadView, MamografiaListView,
   MamografiaCreate, MamografiaUpdateView
)

app_name = "core"

urlpatterns = [
   # path('modelo/', home, name='home'),
   # Pacientes
   path("pacientes/", PacienteListView.as_view(), name="pacientes_list"),
   path("paciente/", PacienteCreateView.as_view(), name="pacientes_create"),
   path("paciente/<int:pk>/", PacienteUpdateView.as_view(), name="pacientes_create"),

   # Mamografia
   path('mamografia/<str:external>/', MamografiaListView.as_view(), name='mamografia_list'),
   path('mamografia/predict/<str:external>/', MamografiaUploadView.as_view(), name='mamografia_predict'),
   path('mamografia/create/<int:result>/<int:mamografia>/', MamografiaCreate.as_view(), name='mamografia_create'),
   path('mamografia/edit/<int:pk>/', MamografiaUpdateView.as_view(), name='mamografia_create'),
   
   
   
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.modelos.views.login.views import LoginView
from apps.modelos.views.signin.views import SignUpView
from django.contrib.auth.views import LogoutView

from apps.home.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='index'),
    path('core/', include('apps.modelos.urls')),
    # LISTAR MAMOGRAFIA
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/modelos/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db import models
from django.conf import settings
from core.settings.develop import MEDIA_URL, STATIC_URL
from django.forms import model_to_dict
import uuid
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError("El email debe ser proporcionado")
        if not username:
            raise ValueError("El nombre de usuario debe ser proporcionado")

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("El superusuario debe tener is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("El superusuario debe tener is_superuser=True.")

        return self.create_user(email, username, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    # Atributo que se utilizará para el inicio de sesión en lugar del campo de nombre de usuario predeterminado
    USERNAME_FIELD = "email"
    # Atributos requeridos al crear un usuario
    REQUIRED_FIELDS = ["username"]

    objects = CustomUserManager()

    class Meta:
        db_table = "custom_user"
        verbose_name = "usuario"
        verbose_name_plural = "usuarios"

    def __str__(self):
        return self.email


class Paciente(models.Model):
    external_id = models.UUIDField(default=uuid.uuid4, editable=False, null=False)
    cedula = models.CharField(max_length=10, blank=False, null=False, unique=True)
    nombre = models.CharField(max_length=350, blank=False, null=False)
    apellido_paterno = models.CharField(max_length=350, blank=False, null=False)
    apellido_materno = models.CharField(max_length=350, blank=False, null=False)
    createdAt = models.DateField("CreatedAt", auto_now=True, auto_now_add=False)
    updatedAt = models.DateField("UpdatedAt", auto_now=True, auto_now_add=False)

    class Meta:
        db_table = "paciente"
        verbose_name = "paciente"
        verbose_name_plural = "pacientes"
        ordering = ["pk"]

    def toJSON(self):
        item = model_to_dict(self)
        item["external_id"] = self.external_id
        return item

    def apellidos(self):
        return f"{self.apellido_paterno} {self.apellido_materno}"

    def __str__(self):
        return self.apellidos() + " " + self.nombre


class Mamografia(models.Model):
    NORMAL = 1
    CANCER = 0

    MAMA_RIGHT = 0
    MAMA_LEFT = 1

    LIST_STATE = (
        (NORMAL, "Nornal"),
        (CANCER, "Cancer"),
    )

    LIST_STATE_POS = (
        (MAMA_RIGHT, "Derecha"),
        (MAMA_LEFT, "Izquierda"),
    )

    external_id = models.UUIDField(default=uuid.uuid4, editable=False, null=False)
    resultado = models.PositiveBigIntegerField(
        default=NORMAL, choices=LIST_STATE, blank=False, null=False
    )
    lado_mamario = models.PositiveBigIntegerField(
        default=MAMA_RIGHT, choices=LIST_STATE_POS, blank=False, null=False
    )
    descripcion = models.CharField(max_length=1024, blank=True, null=True)
    createdAt = models.DateField("CreatedAt", auto_now=True, auto_now_add=False)
    updatedAt = models.DateField("UpdatedAt", auto_now=True, auto_now_add=False)
    paciente = models.ForeignKey(
        Paciente, related_name="paciente", on_delete=models.CASCADE, null=False
    )

    class Meta:
        db_table = "mamografia"
        verbose_name = "mamografia"
        verbose_name_plural = "mamografias"
        ordering = ["pk"]

    def toJSON(self):
        item = model_to_dict(self)
        item["external_id"] = self.external_id
        item["createdAt"] = self.createdAt
        return item

    def __str__(self):
        return str(self.paciente.nombre)


class MamografiaImage(models.Model):
    VERTICAL = 0
    HORIZONTAL = 1
    LIST_STATE = (
        (VERTICAL, "Vertical"),
        (HORIZONTAL, "Horizontal"),
    )

    external_id = models.UUIDField(default=uuid.uuid4, editable=False, null=False)
    imagen = models.ImageField(
        upload_to="mamografia/%Y/%m/%d",
        null=True,
        blank=True,
        verbose_name="mamografia",
    )
    orientacion = models.PositiveBigIntegerField(
        default=(VERTICAL), choices=LIST_STATE, blank=False, null=False
    )
    createdAt = models.DateField("CreatedAt", auto_now=True, auto_now_add=False)
    updatedAt = models.DateField("UpdatedAt", auto_now=True, auto_now_add=False)
    mamografia = models.ForeignKey(
        Mamografia, verbose_name="mamografia_image", on_delete=models.CASCADE
    )

    class Meta:
        db_table = "mamografia_image"
        verbose_name = "mamografia_image"
        verbose_name_plural = "mamografia_images"
        ordering = ["pk"]


class MamografiaUploadFile(models.Model):
    DERECHA = 0
    IZQUIERDA = 1
    LIST_STATE = (
        (DERECHA, "Derecha"),
        (IZQUIERDA, "Izquierda"),
    )

    imagen_horizontal = models.ImageField(
        upload_to="mamografia/%Y/%m/%d",
        null=True,
        blank=True,
        verbose_name="horizontal",
    )
    imagen_vertical = models.ImageField(
        upload_to="mamografia/%Y/%m/%d", null=True, blank=True, verbose_name="vertical"
    )
    lado_mamario = models.PositiveBigIntegerField(
        default=DERECHA,
        choices=LIST_STATE,
    )
    descripcion = models.CharField(max_length=1024, blank=True, null=True)
    paciente = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = "mamografia_upload"
        verbose_name = "mamografia_upload"
        verbose_name_plural = "mamografia_uploads"
        ordering = ["pk"]


@receiver(pre_save, sender=MamografiaUploadFile)
def pre_save_receiver(sender, instance, **kwargs):
    from apps.modelos.layers.application.service_app_upload_images import (
        MamografiaAppService,
    )

    MamografiaAppService.pre_procesar_datos()


@receiver(post_save, sender=MamografiaUploadFile)
def post_save_receiver(sender, instance, **kwargs):
    from apps.modelos.layers.application.service_app_upload_images import (
        MamografiaAppService,
    )

    MamografiaAppService.procesar_datos(instance)

apps/modelos/views/login/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from apps.modelos.forms import *  # Importar solo los formularios necesarios o especificar cada formulario por separado
from apps.modelos.models import *  # Importar solo los modelos necesarios o especificar cada modelo por separado
from django.views.decorators.csrf import csrf_exempt  


class LoginView(LoginView):
    model = Mamografia
    fields = '__all__'
    template_name = 'registration/login.html'
    success_url = reverse_lazy('core:pacientes_list')

    @csrf_exempt  # Añadir protección CSRF a la vista
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_success_url(self):
        return self.success_url
    
    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))







apps/modelos/views/mamografia/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic import CreateView, ListView, UpdateView
from apps.modelos.models import Mamografia, MamografiaImage, MamografiaUploadFile
from apps.modelos.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.modelos.layers.application.service_app_upload_images import MamografiaAppService



class MamografiaListView(LoginRequiredMixin, ListView):
    model = Mamografia
    template_name = "mamografia/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Mamografias"
        context["entity"] = "Mamografia"
        context["mamografia"] = Mamografia.objects.filter(
            paciente__external_id=self.kwargs.get("external")
        )
        context["create_url"] = reverse_lazy(
            "core:mamografia_predict", args=[self.kwargs.get("external")]
        )
        context["list_url"] = reverse_lazy(
            "core:mamografia_list", args=[self.kwargs.get("external")]
        )
        return context

    @method_decorator(csrf_exempt, login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST["action"]
            if action == "searchdata":
                data = []
                for i in Mamografia.objects.filter(
                    paciente__external_id=kwargs.get("external")
                ):
                    data.append(i.toJSON())
            else:
                data["error"] = "Ha ocurrido un error"
        except Exception as e:
            data["error"] = str(e)
        return JsonResponse(data, safe=False)


class MamografiaUploadView(LoginRequiredMixin, CreateView):
    model = MamografiaUploadFile
    form_class = MamografiaUploadForm
    template_name = "mamografia/predict.html"

    def get_context_data(self, **kwargs):
        context = super(MamografiaUploadView, self).get_context_data(**kwargs)
        context["title"] = "Registro de Mamografias"
        context["entity"] = "Mamografias"
        context["list_url"] = self.success_url
        context["action"] = "add"
        context["paciente"] = Paciente.objects.get(
            external_id=self.kwargs.get("external")
        )
        if self.form_class not in context:
            context["form"] = MamografiaUploadForm(external=self.kwargs.get("external"))
        return context

    @method_decorator(csrf_exempt, login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            external_id = self.kwargs.get("external")
            mamografia_upload = form.save(commit=False)
            mamografia_upload.paciente = external_id
            mamografia_upload.save()

            # Llama al servicio para procesar la mamografía y obtener el resultado
            resultado = MamografiaAppService.procesar_datos(mamografia_upload)
            return redirect(
                "core:mamografia_create",
                result=(
                    1 if float(resultado[0]) > 0.5 and float(resultado[1]) > 0.5 else 0
                ),
                mamografia=mamografia_upload.id,
            )


class MamografiaCreate(LoginRequiredMixin, CreateView):
    model = Mamografia
    form_class = MamografiaForm
    template_name = "mamografia/create.html"
    success_url = reverse_lazy("core:pacientes_list")

    def get_context_data(self, **kwargs):
        context = super(MamografiaCreate, self).get_context_data(**kwargs)
        context["title"] = "Resultado de Mamografia"
        context["entity"] = "Mamografias"
        context["list_url"] = self.success_url
        context["action"] = "add"
        context["mamografia"] = MamografiaUploadFile.objects.get(
            id=self.kwargs.get("mamografia")
        )
        context["prediction"] = self.kwargs.get("result")
        if "form" not in context:
            context["form"] = self.form_class()
        return context

    def form_valid(self, form):
        mamografia_upload = MamografiaUploadFile.objects.get(
            id=self.kwargs.get("mamografia")
        )
        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.paciente = Paciente.objects.get(
                external_id=mamografia_upload.paciente
            )
            form_instance.save()
            MamografiaImage.objects.create(
                imagen=mamografia_upload.imagen_horizontal.url.replace("/media", ""),
                orientacion=1,
                mamografia=form_instance,
            )
            MamografiaImage.objects.create(
                imagen=mamografia_upload.imagen_vertical.url.replace("/media", ""),
                orientacion=0,
                mamografia=form_instance,
            )
            return HttpResponseRedirect(self.success_url)  # Redirige a la URL de éxito

        return super().form_invalid(form)

    @method_decorator(csrf_exempt, login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class MamografiaUpdateView(LoginRequiredMixin, UpdateView):
    model = Mamografia
    form_class = MamografiaForm
    template_name = "mamografia/create.html"
    success_url = reverse_lazy("core:pacientes_list")

    def get_context_data(self, **kwargs):
        context = super(MamografiaUpdateView, self).get_context_data(**kwargs)
        context["title"] = "Resultado de Mamografia"
        context["entity"] = "Mamografias"
        context["list_url"] = self.success_url
        context["action"] = "edit"
        context["mamografia"] = Mamografia.objects.get(id=self.kwargs.get("pk"))
        context["imagen"] = MamografiaImage.objects.filter(
            mamografia__id=self.kwargs.get("pk")
        )
        if "form" not in context:
            context["form"] = self.form_class()
        return context

    def form_valid(self, form):
        mamografia_upload = Mamografia.objects.get(id=self.kwargs.get("pk"))
        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.paciente = Paciente.objects.get(
                external_id=mamografia_upload.paciente.external_id
            )
            form_instance.save()
            return HttpResponseRedirect(self.success_url)  # Redirige a la URL de éxito

        return super().form_invalid(form)

    @method_decorator(csrf_exempt, login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

apps/modelos/templates/mamografia/crearMamo.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body_url %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'core:pacientes_list' %}" class="active">Catalog</a></li>
</ol>
{% endblock %}

{% block content %}
<div class="card ml-5 mr-5 p-4">
    <div class="card-body">
        <h3><span class="badge bg-primary mr-4">Paciente Seleccionado: </span>{{paciente|upper}}</h3>

        <form method="post" action="" enctype="multipart/form-data">
            <input type="hidden" value="{{action}}" name="action">
        <div class="row">
                <div class="form-group col-6">
                    <h4><span class="badge bg-secondary mr-4">Vertical </span></h4>
                    {{ form_image_right.imagen }}
                </div>
                <div class="form-group col-6">
                    <h4><span class="badge bg-secondary mr-4">Horizontal </span></h4>
                    {{ form_image_left.imagen|attr:"class:image_left"}} 
                </div>
                <div class="col-6 text-center">
                    <img src="{% static '\img\empty.png' %}" width="400px" height="300px" id="image_right">
                </div>
                <div class="col-6  text-center">
                    <img src="{% static '\img\empty.png' %}" width="400px" height="300px" id="image_left">

                </div>
            </div>
            <hr>
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Confirmar</button>
            <a href="{% url 'core:pacientes_list' %}" class="btn btn-outline-secondary">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    function readURL(input, image) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                // Asignamos el atributo src a la tag de imagen
                $('#' + image).attr('src', e.target.result);
                //$('#image_right').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    // El listener va asignado al input
    $("#id_imagen").change(function () {
        readURL(this, "image_right");
    });
    $(".image_left").change(function () {
        readURL(this, "image_left");
    });

</script>
{% endblock %}

apps/modelos/templates/mamografia/create.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body_url %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'core:pacientes_list' %}" class="active">Mamografía</a></li>
</ol>
{% endblock %}

{% block content %}

<div class="card ml-5 mr-5 p-4">

    <div class="card-body">
        <form method="post" action=".">
            <div class="row d-flex justify-content-start align-items-start">
                <div class="form-group col-12">
                    <label for="id_resultado">Lado Mamario</label>
                    <select name="lado_mamario" id="id_lado_mamario" class="form-control">
                        <option value="">Seleccione</option>
                        <option value="0" {%if mamografia.lado_mamario == 0 %} selected {% endif %}> Mama Derecha</option>
                        <option value="1" {%if mamografia.lado_mamario == 1 %} selected {% endif %}> Mama Izquierda</option>
                    </select>
                </div>
                <div class="col-6 ">
                    <h3><span class="badge bg-primary mr-4">Vertical </span></h3>
                    <img src="{% if mamografia.imagen_vertical %} {{mamografia.imagen_vertical.url}} {% else %} {{imagen.1.imagen.url}} {% endif %}" width="400px" height="300px" id="image_left">
                </div>
                <div class="col-6">
                    <h3><span class="badge bg-primary mr-4">Horizontal </span></h3>
                    <img src="{% if mamografia.imagen_horizontal %} {{mamografia.imagen_horizontal.url}} {% else %} {{imagen.0.imagen.url}} {% endif %}" width="400px" height="300px" id="image_right">
                </div>
            </div>
            <hr>
            <div class="form-group">
                <label for="id_resultado">Resultado</label>
                <select name="resultado" id="id_resultado" class="form-control">
                    <option value="">Seleccione</option>
                    <option value="0" {%if prediction == 0  or mamografia.resultado == 0 %} selected {% endif %}>Cancer</option>
                    <option value="1" {%if prediction == 1 or mamografia.resultado == 1 %} selected {% endif %}>Normal</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_descripcion">Descripcion</label>
                <input type="text" name="descripcion" class="form-control" required maxlenght="'1024" id="id_descripcion" value="{% if prediction == 0 %} En las imágenes se ha detectado Cáncer {% else %} En las imágenes no se ha detectado Cáncer {% endif %}">
            </div>

            <div class="text-center p-2">
                <button type="submit" class="btn btn-primary mr-3">Confirmar</button>
                <a href="{% url 'core:pacientes_list' %}" class="btn btn-outline-secondary">Cancelar</a>
            </div>
        </form>
    </div>

</div>
{% endblock %}

{% block javascript %}
    
{% endblock %}

apps/modelos/templates/mamografia/list.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
<script src="{% static 'mamografia/list.js' %}"></script>
<script src="{% static 'mamografia/moment.js' %}"></script>
{% endblock %}



{% block body_url %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'core:mamografia_list' 0 %}" class="active">Mamografia</a></li>
</ol>
{% endblock %}

{% block columns %}
<tr>
    <th scope="col" style="width: 10%;">#</th>
    <th scope="col" style="width: 30%;">Fecha</th>
    <th scope="col" style="width: 20%;">Orientacion</th>
    <th scope="col" style="width: 20%;">Resultado</th>
    <th scope="col" style="width: 30%;">Opciones</th>
    
</tr>
{% endblock %}

{% block rows %}

{% endblock %}


{% block javascript %}

{% endblock %}

apps/modelos/templates/mamografia/predict.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body_url %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'core:pacientes_list' %}" class="active">Mamografía</a></li>
</ol>
{% endblock %}

{% block content %}

<div class="card ml-5 mr-5 p-4">
    {% if not mamografia %}
    <div class="card-body">
        <h3><span class="badge bg-primary mr-4">Paciente Seleccionado: </span>{{paciente|title}}</h3>

        <form method="post" action="" enctype="multipart/form-data">
            <input type="hidden" value="{{action}}" name="action">
            <div class="form-group">
                {{ form.paciente}}
            </div>
            <div class="form-group">
                <label for="lado_mamario">Lado mamario</label>
                {{ form.lado_mamario}}
            </div>
            <div class="row">
                <div class="form-group col-6">
                    <h4><span class="badge bg-secondary mr-4">Vertical </span></h4>
                    <div class="col-6 text-center">
                        <img src="{% static '\img\empty.png' %}" width="400px" height="300px" id="image_left">
                    </div>
                    {{ form.imagen_vertical}}
                    
                </div>
                <div class="form-group col-6">
                    <h4><span class="badge bg-secondary mr-4">Horizontal </span></h4>
                    <div class="col-6  text-center">
                        <img src="{% static '\img\empty.png' %}" width="400px" height="300px" id="image_right">
                    </div>
                    {{ form.imagen_horizontal }}
                </div>
                
            </div>
            <hr>

            <div class="text-center p-2">
                <button type="submit" class="btn btn-primary mr-3">Confirmar</button>
                <a href="{% url 'core:pacientes_list' %}" class="btn btn-outline-secondary">Cancelar</a>
            </div>

        </form>
    </div>
    {% else %}
    <div class="row justify-content-center align-items-center">
        <div  class="col-8 text-center">
            <div class=" alert alert-warning" role="alert">
                No tienes regisgrado ninguna mamografía, prueba a crearla 
            </div>
            <a href="#" class="btn btn-primary">
                <i class="fas fa-plus"></i>  Añadir mamografia
            </a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    function readURL(input, image) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                // Asignamos el atributo src a la tag de imagen
                $('#' + image).attr('src', e.target.result);
                //$('#image_right').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    // El listener va asignado al input
    $("#imagen_vertical").change(function () {
        readURL(this, "image_left");
    });
    $("#imagen_horizontal").change(function () {
        readURL(this, "image_right");
    });
</script>
{% endblock %}